stages:
  - test
  - build
  - deploy

go-test:
  image: golang:alpine
  stage: test
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -short $(go list ./... | grep -v /vendor/)

image-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - master

image-deploy:
  image:
    name: alpine:latest
  stage: deploy
  script:
    - apk add --no-cache git curl bash
    - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - cd deployment
    - ../kustomize edit set image prestrafe-gsi=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - rm ../kustomize
    - cd ..
    - git add deployment/kustomization.yaml
    - git commit -m "Deploy revision $CI_COMMIT_SHORT_SHA via kustomize"
    - git push -u origin $CI_COMMIT_BRANCH
