apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: prestrafe-gsi
  newName: registry.gitlab.com/prestrafe-twitchbot/prestrafe-gsi
  newTag: 39ba8231
- name: prestrafe-gsi:latest
  newName: prestrafe-gsi
  newTag: commit

resources:
- deployment.yaml
- service.yaml
