apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prestrafe-gsi
  labels:
    release: monitoring
spec:
  endpoints:
    - honorLabels: true
      targetPort: http-metrics
  namespaceSelector:
    matchNames:
      - prestrafe
  selector:
    matchLabels:
      app: prestrafe-gsi
