apiVersion: v1
kind: Service
metadata:
  name: gsi
spec:
  ports:
    - name: svc-gsi
      port: 8080
      targetPort: http-gsi
      protocol: TCP
    - name: svc-metrics
      port: 9080
      targetPort: http-metrics
      protocol: TCP
  selector:
    app: prestrafe-gsi
